# Generated by Django 5.1.4 on 2025-01-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurban', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
