# Generated by Django 5.1.4 on 2025-01-08 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kurban', '0002_episode_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='video_url',
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='episode_videos/'),
        ),
    ]
